

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1321, 1277)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("\n"
"background-color: rgb(0,0,0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tab_frame = QtWidgets.QFrame(self.centralwidget)
        self.tab_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tab_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tab_frame.setObjectName("tab_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cam_frame = QtWidgets.QFrame(self.tab_frame)
        self.cam_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cam_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cam_frame.setObjectName("cam_frame")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.cam_frame)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.cam_label = QtWidgets.QLabel(self.cam_frame)
        self.cam_label.setMinimumSize(QtCore.QSize(600, 400))
        self.cam_label.setMaximumSize(QtCore.QSize(500, 500))
        self.cam_label.setText("")
        self.cam_label.setPixmap(QtGui.QPixmap(":/other/images/nature-5879588_960_720.jpg"))
        self.cam_label.setScaledContents(True)
        self.cam_label.setWordWrap(False)
        self.cam_label.setObjectName("cam_label")
        self.horizontalLayout_11.addWidget(self.cam_label)
        self.horizontalLayout.addWidget(self.cam_frame)
        self.Egn_psla_frame = QtWidgets.QFrame(self.tab_frame)
        self.Egn_psla_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Egn_psla_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Egn_psla_frame.setObjectName("Egn_psla_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Egn_psla_frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.compass_Frame = QtWidgets.QFrame(self.Egn_psla_frame)
        self.compass_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.compass_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.compass_Frame.setObjectName("compass_Frame")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.compass_Frame)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_2 = QtWidgets.QLabel(self.compass_Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(200, 200))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/other/images/resim_1 arti_hor.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_13.addWidget(self.label_2)
        self.verticalLayout_3.addWidget(self.compass_Frame)
        self.Gyro_frame = QtWidgets.QFrame(self.Egn_psla_frame)
        self.Gyro_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Gyro_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Gyro_frame.setObjectName("Gyro_frame")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.Gyro_frame)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label = QtWidgets.QLabel(self.Gyro_frame)
        self.label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(200, 200))
        self.label.setMaximumSize(QtCore.QSize(200, 200))
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/other/images/Pusula.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        self.horizontalLayout_10.addWidget(self.label)
        self.verticalLayout_3.addWidget(self.Gyro_frame)
        self.horizontalLayout.addWidget(self.Egn_psla_frame)
        self.plane_Status_frame = QtWidgets.QFrame(self.tab_frame)
        self.plane_Status_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plane_Status_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plane_Status_frame.setObjectName("plane_Status_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.plane_Status_frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.auto_mode_frame = QtWidgets.QFrame(self.plane_Status_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.auto_mode_frame.sizePolicy().hasHeightForWidth())
        self.auto_mode_frame.setSizePolicy(sizePolicy)
        self.auto_mode_frame.setStyleSheet("background-color: rgb(66, 66, 66);\n"
"color: rgb(255, 255, 255);")
        self.auto_mode_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.auto_mode_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.auto_mode_frame.setObjectName("auto_mode_frame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.auto_mode_frame)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.Auoo_btn = QtWidgets.QPushButton(self.auto_mode_frame)
        self.Auoo_btn.setObjectName("Auoo_btn")
        self.horizontalLayout_9.addWidget(self.Auoo_btn)
        self.manuel_btn = QtWidgets.QPushButton(self.auto_mode_frame)
        self.manuel_btn.setObjectName("manuel_btn")
        self.horizontalLayout_9.addWidget(self.manuel_btn)
        self.verticalLayout_4.addWidget(self.auto_mode_frame)
        self.Plane_status_frame = QtWidgets.QFrame(self.plane_Status_frame)
        self.Plane_status_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Plane_status_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Plane_status_frame.setObjectName("Plane_status_frame")
        self.verticalLayout_4.addWidget(self.Plane_status_frame)
        self.horizontalLayout.addWidget(self.plane_Status_frame)
        self.Data_mages = QtWidgets.QFrame(self.tab_frame)
        self.Data_mages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Data_mages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Data_mages.setObjectName("Data_mages")
        self.gridLayout = QtWidgets.QGridLayout(self.Data_mages)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_3 = QtWidgets.QFrame(self.Data_mages)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout.addWidget(self.frame_3, 0, 2, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.Data_mages)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout.addWidget(self.frame_5, 1, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.Data_mages)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout.addWidget(self.frame_4, 1, 1, 1, 2)
        self.frame = QtWidgets.QFrame(self.Data_mages)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 2)
        self.horizontalLayout.addWidget(self.Data_mages)
        self.verticalLayout.addWidget(self.tab_frame)
        self.bot_frame = QtWidgets.QFrame(self.centralwidget)
        self.bot_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bot_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bot_frame.setObjectName("bot_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.bot_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Telemetri_frame = QtWidgets.QFrame(self.bot_frame)
        self.Telemetri_frame.setMaximumSize(QtCore.QSize(800, 800))
        self.Telemetri_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.Telemetri_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Telemetri_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Telemetri_frame.setObjectName("Telemetri_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Telemetri_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.menu_frame = QtWidgets.QFrame(self.Telemetri_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_frame.sizePolicy().hasHeightForWidth())
        self.menu_frame.setSizePolicy(sizePolicy)
        self.menu_frame.setStyleSheet("background-color: rgb(66, 66, 66);")
        self.menu_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_frame.setObjectName("menu_frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.menu_frame)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.controller_btn = QtWidgets.QPushButton(self.menu_frame)
        self.controller_btn.setObjectName("controller_btn")
        self.horizontalLayout_7.addWidget(self.controller_btn)
        self.Null1_btn = QtWidgets.QPushButton(self.menu_frame)
        self.Null1_btn.setObjectName("Null1_btn")
        self.horizontalLayout_7.addWidget(self.Null1_btn)
        self.Null2_btn = QtWidgets.QPushButton(self.menu_frame)
        self.Null2_btn.setObjectName("Null2_btn")
        self.horizontalLayout_7.addWidget(self.Null2_btn)
        self.verticalLayout_2.addWidget(self.menu_frame)
        self.Stacked_frame = QtWidgets.QFrame(self.Telemetri_frame)
        self.Stacked_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Stacked_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Stacked_frame.setObjectName("Stacked_frame")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.Stacked_frame)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.stackedWidget = QtWidgets.QStackedWidget(self.Stacked_frame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.controller_page = QtWidgets.QWidget()
        self.controller_page.setObjectName("controller_page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.controller_page)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(15)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.controll_Header_frame = QtWidgets.QFrame(self.controller_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controll_Header_frame.sizePolicy().hasHeightForWidth())
        self.controll_Header_frame.setSizePolicy(sizePolicy)
        self.controll_Header_frame.setStyleSheet("QFrame{\n"
"border-color:rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 0px 0px 2px 0px;\n"
"}\n"
"QLabel{\n"
"border-style: solid;\n"
"border-width: 0px 0px 0px 0px;\n"
"}")
        self.controll_Header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.controll_Header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.controll_Header_frame.setObjectName("controll_Header_frame")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.controll_Header_frame)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_3 = QtWidgets.QLabel(self.controll_Header_frame)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_15.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.controll_Header_frame)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_15.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.controll_Header_frame)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_15.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.controll_Header_frame)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_15.addWidget(self.label_6)
        self.verticalLayout_5.addWidget(self.controll_Header_frame)
        self.controller_page_Menu_frame = QtWidgets.QFrame(self.controller_page)
        self.controller_page_Menu_frame.setStyleSheet("QFrame{\n"
"border-color:rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 0px 2px 0px 0px;\n"
"}\n"
"QLabel{\n"
"border-style: solid;\n"
"border-width: 0px 0px 0px 0px;\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(66, 66, 66);\n"
"}")
        self.controller_page_Menu_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.controller_page_Menu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.controller_page_Menu_frame.setObjectName("controller_page_Menu_frame")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.controller_page_Menu_frame)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.Controller_page_menu_left_frame = QtWidgets.QFrame(self.controller_page_Menu_frame)
        self.Controller_page_menu_left_frame.setStyleSheet("")
        self.Controller_page_menu_left_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Controller_page_menu_left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Controller_page_menu_left_frame.setObjectName("Controller_page_menu_left_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Controller_page_menu_left_frame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.Controller_page_menu_left_frame)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.Controller_page_menu_left_frame)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.Controller_page_menu_left_frame)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_6.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.Controller_page_menu_left_frame)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_6.addWidget(self.label_10)
        self.horizontalLayout_16.addWidget(self.Controller_page_menu_left_frame)
        self.Controller_page_menu_left_menu_frame = QtWidgets.QFrame(self.controller_page_Menu_frame)
        self.Controller_page_menu_left_menu_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Controller_page_menu_left_menu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Controller_page_menu_left_menu_frame.setObjectName("Controller_page_menu_left_menu_frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.Controller_page_menu_left_menu_frame)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_13 = QtWidgets.QLabel(self.Controller_page_menu_left_menu_frame)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_7.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.Controller_page_menu_left_menu_frame)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_7.addWidget(self.label_14)
        self.label_12 = QtWidgets.QLabel(self.Controller_page_menu_left_menu_frame)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_7.addWidget(self.label_12)
        self.label_11 = QtWidgets.QLabel(self.Controller_page_menu_left_menu_frame)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_7.addWidget(self.label_11)
        self.horizontalLayout_16.addWidget(self.Controller_page_menu_left_menu_frame)
        self.Controller_page_menu_right_menu_frame = QtWidgets.QFrame(self.controller_page_Menu_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Controller_page_menu_right_menu_frame.sizePolicy().hasHeightForWidth())
        self.Controller_page_menu_right_menu_frame.setSizePolicy(sizePolicy)
        self.Controller_page_menu_right_menu_frame.setMaximumSize(QtCore.QSize(16777215, 300))
        self.Controller_page_menu_right_menu_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Controller_page_menu_right_menu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Controller_page_menu_right_menu_frame.setObjectName("Controller_page_menu_right_menu_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Controller_page_menu_right_menu_frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.Controller_page_menu_right_menu_frame)
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 3, 0, 1, 2)
        self.label_16 = QtWidgets.QLabel(self.Controller_page_menu_right_menu_frame)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 0, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.Controller_page_menu_right_menu_frame)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 1, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.Controller_page_menu_right_menu_frame)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 0, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.Controller_page_menu_right_menu_frame)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 1, 1, 1, 1)
        self.horizontalSlider = QtWidgets.QSlider(self.Controller_page_menu_right_menu_frame)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout_2.addWidget(self.horizontalSlider, 2, 0, 1, 2)
        self.horizontalLayout_16.addWidget(self.Controller_page_menu_right_menu_frame)
        self.Controller_page_menu_right_frame = QtWidgets.QFrame(self.controller_page_Menu_frame)
        self.Controller_page_menu_right_frame.setMaximumSize(QtCore.QSize(16777215, 300))
        self.Controller_page_menu_right_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Controller_page_menu_right_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Controller_page_menu_right_frame.setObjectName("Controller_page_menu_right_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Controller_page_menu_right_frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_22 = QtWidgets.QLabel(self.Controller_page_menu_right_frame)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 0, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.Controller_page_menu_right_frame)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 0, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.Controller_page_menu_right_frame)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 1, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.Controller_page_menu_right_frame)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 1, 1, 1, 1)
        self.horizontalSlider_2 = QtWidgets.QSlider(self.Controller_page_menu_right_frame)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.gridLayout_3.addWidget(self.horizontalSlider_2, 2, 0, 1, 2)
        self.pushButton_2 = QtWidgets.QPushButton(self.Controller_page_menu_right_frame)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 3, 0, 1, 2)
        self.horizontalLayout_16.addWidget(self.Controller_page_menu_right_frame)
        self.verticalLayout_5.addWidget(self.controller_page_Menu_frame)
        self.contoler_page_footer_frame = QtWidgets.QFrame(self.controller_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contoler_page_footer_frame.sizePolicy().hasHeightForWidth())
        self.contoler_page_footer_frame.setSizePolicy(sizePolicy)
        self.contoler_page_footer_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contoler_page_footer_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contoler_page_footer_frame.setObjectName("contoler_page_footer_frame")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.contoler_page_footer_frame)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.QR_code_Name_label = QtWidgets.QLabel(self.contoler_page_footer_frame)
        self.QR_code_Name_label.setObjectName("QR_code_Name_label")
        self.horizontalLayout_14.addWidget(self.QR_code_Name_label)
        self.QR_code_data_label = QtWidgets.QLabel(self.contoler_page_footer_frame)
        self.QR_code_data_label.setObjectName("QR_code_data_label")
        self.horizontalLayout_14.addWidget(self.QR_code_data_label)
        self.verticalLayout_5.addWidget(self.contoler_page_footer_frame)
        self.stackedWidget.addWidget(self.controller_page)
        self.Null_page = QtWidgets.QWidget()
        self.Null_page.setObjectName("Null_page")
        self.stackedWidget.addWidget(self.Null_page)
        self.horizontalLayout_12.addWidget(self.stackedWidget)
        self.verticalLayout_2.addWidget(self.Stacked_frame)
        self.horizontalLayout_2.addWidget(self.Telemetri_frame)
        self.Map_frame = QtWidgets.QFrame(self.bot_frame)
        self.Map_frame.setMaximumSize(QtCore.QSize(16777210, 16777215))
        self.Map_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Map_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Map_frame.setObjectName("Map_frame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.Map_frame)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.mp_label = QtWidgets.QLabel(self.Map_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mp_label.sizePolicy().hasHeightForWidth())
        self.mp_label.setSizePolicy(sizePolicy)
        self.mp_label.setMaximumSize(QtCore.QSize(1000, 1300))
        self.mp_label.setText("")
        self.mp_label.setPixmap(QtGui.QPixmap(":/other/images/B777_PFD.png"))
        self.mp_label.setScaledContents(False)
        self.mp_label.setWordWrap(False)
        self.mp_label.setOpenExternalLinks(False)
        self.mp_label.setObjectName("mp_label")
        self.horizontalLayout_8.addWidget(self.mp_label)
        self.horizontalLayout_2.addWidget(self.Map_frame)
        self.verticalLayout.addWidget(self.bot_frame)
        self.footer_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.footer_frame.sizePolicy().hasHeightForWidth())
        self.footer_frame.setSizePolicy(sizePolicy)
        self.footer_frame.setStyleSheet("background-color: rgb(66, 66, 66);")
        self.footer_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.footer_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.footer_frame.setObjectName("footer_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.footer_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.left_footer_frame = QtWidgets.QFrame(self.footer_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_footer_frame.sizePolicy().hasHeightForWidth())
        self.left_footer_frame.setSizePolicy(sizePolicy)
        self.left_footer_frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.left_footer_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_footer_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_footer_frame.setObjectName("left_footer_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.left_footer_frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cop_label = QtWidgets.QLabel(self.left_footer_frame)
        self.cop_label.setStyleSheet("COLOR : rgb(211, 193, 207)")
        self.cop_label.setObjectName("cop_label")
        self.horizontalLayout_4.addWidget(self.cop_label)
        self.horizontalLayout_3.addWidget(self.left_footer_frame)
        self.top_footer_frame = QtWidgets.QFrame(self.footer_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top_footer_frame.sizePolicy().hasHeightForWidth())
        self.top_footer_frame.setSizePolicy(sizePolicy)
        self.top_footer_frame.setStyleSheet("")
        self.top_footer_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_footer_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_footer_frame.setObjectName("top_footer_frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.top_footer_frame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.null_frame = QtWidgets.QLabel(self.top_footer_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.null_frame.sizePolicy().hasHeightForWidth())
        self.null_frame.setSizePolicy(sizePolicy)
        self.null_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.null_frame.setObjectName("null_frame")
        self.horizontalLayout_6.addWidget(self.null_frame)
        self.horizontalLayout_3.addWidget(self.top_footer_frame)
        self.right_footer_frame = QtWidgets.QFrame(self.footer_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_footer_frame.sizePolicy().hasHeightForWidth())
        self.right_footer_frame.setSizePolicy(sizePolicy)
        self.right_footer_frame.setStyleSheet("\n"
"border:none;\n"
"")
        self.right_footer_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_footer_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_footer_frame.setObjectName("right_footer_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.right_footer_frame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.insta_btn = QtWidgets.QPushButton(self.right_footer_frame)
        self.insta_btn.setMinimumSize(QtCore.QSize(40, 0))
        self.insta_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/other/images/3955024.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.insta_btn.setIcon(icon)
        self.insta_btn.setIconSize(QtCore.QSize(32, 32))
        self.insta_btn.setObjectName("insta_btn")
        self.horizontalLayout_5.addWidget(self.insta_btn)
        self.info_btn = QtWidgets.QPushButton(self.right_footer_frame)
        self.info_btn.setMinimumSize(QtCore.QSize(40, 0))
        self.info_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/other/images/604573.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.info_btn.setIcon(icon1)
        self.info_btn.setIconSize(QtCore.QSize(32, 32))
        self.info_btn.setObjectName("info_btn")
        self.horizontalLayout_5.addWidget(self.info_btn)
        self.horizontalLayout_3.addWidget(self.right_footer_frame)
        self.verticalLayout.addWidget(self.footer_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Auoo_btn.setText(_translate("MainWindow", "OTTONOM"))
        self.manuel_btn.setText(_translate("MainWindow", "MANUEL"))
        self.controller_btn.setText(_translate("MainWindow", "Controller"))
        self.Null1_btn.setText(_translate("MainWindow", "NULL"))
        self.Null2_btn.setText(_translate("MainWindow", "NULL"))
        self.label_3.setText(_translate("MainWindow", "NULL"))
        self.label_4.setText(_translate("MainWindow", "NULL"))
        self.label_5.setText(_translate("MainWindow", "HAVA_HIZI[M/S]"))
        self.label_6.setText(_translate("MainWindow", "İRTİFA[m]"))
        self.label_7.setText(_translate("MainWindow", "İRTİFA"))
        self.label_8.setText(_translate("MainWindow", "Yer HIzı"))
        self.label_9.setText(_translate("MainWindow", "BATARYA"))
        self.label_10.setText(_translate("MainWindow", "ivme[m/s2]"))
        self.label_13.setText(_translate("MainWindow", "982.2"))
        self.label_14.setText(_translate("MainWindow", "10.5"))
        self.label_12.setText(_translate("MainWindow", "%45"))
        self.label_11.setText(_translate("MainWindow", "+2"))
        self.pushButton.setText(_translate("MainWindow", "GÖNDER"))
        self.label_16.setText(_translate("MainWindow", "12.3"))
        self.label_17.setText(_translate("MainWindow", "HEDEF"))
        self.label_15.setText(_translate("MainWindow", "DURUM"))
        self.label_18.setText(_translate("MainWindow", "15.0"))
        self.label_22.setText(_translate("MainWindow", "DURUM"))
        self.label_19.setText(_translate("MainWindow", "12.3"))
        self.label_21.setText(_translate("MainWindow", "HEDEF"))
        self.label_20.setText(_translate("MainWindow", "15.0"))
        self.pushButton_2.setText(_translate("MainWindow", "Gönder"))
        self.QR_code_Name_label.setText(_translate("MainWindow", "QR_CODE"))
        self.QR_code_data_label.setText(_translate("MainWindow", "25-45-86"))
        self.cop_label.setText(_translate("MainWindow", "ALYA SİHA ©2023  All rights reserved"))
        self.null_frame.setText(_translate("MainWindow", "NULL"))
import icon_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
